- platform: generic_thermostat
  name: "Termostato virtual"
  unique_id: "termostato_virtual"
  heater: switch.alias_caldera
  target_sensor: sensor.confort_termico
  min_temp: 0
  max_temp: 24
  ac_mode: false
  cold_tolerance: 0.5
  hot_tolerance: 0.5
  precision: 0.1
  target_temp_step: 0.1
