- platform: bluetooth_le_tracker
  interval_seconds: 60
  consider_home: 180
  new_device_defaults:
  track_new_devices: true


- platform: nmap_tracker
  name: Tracked Object
  latitude: "{{ state_attr('sensor.fgc_sqv', 'latitude') }}"
  longitude: "{{ state_attr('sensor.fgc_sqv', 'longitude') }}"
  source_type: gps
