- platform: template
  sensors:
    humedad_exterior:
      friendly_name: "Humedad Exterior"
      device_class: humidity
      unit_of_measurement: '%'
      unique_id: "humedad_exterior"
      value_template: "
      {# https://www.pacienciadigital.com/redundancia-sensores-home-assistant/ #}
      {% set sensor1 = 'sensor.aemet_humidity' %}
      {% set sensor2 = 'sensor.st_quirze_del_v_vallsuau_barcelona_humidity' %}
      {% set timeout=600 %} {# tiempo límite en segundos #}
      {# establecemos código -99 si no es un número #}
      {% set sensor1_value = states(sensor1) |float |default(-99,true) %}
      {% set sensor2_value = states(sensor2) |float |default(-99,true) %}
      {% set sensor1_valid=(sensor1_value!=-99) %}
      {% set sensor2_valid=(sensor1_value!=-99) %}
      {% if sensor1_valid and sensor2_valid  %}
          {{ (sensor1_value+sensor2_value)/2 }}      
      {% elif sensor1_valid and not sensor2_valid %}
          {{ sensor1_value }}
      {% elif not sensor1_valid and sensor2_valid and not sensor3_valid %}
          {{ sensor2_value }}
      
      {# 3 instrumentos fallando #}
      {% else %}
          'Fallo'        
      {% endif %}    
      "
      icon_template: mdi:calculator

    temperatura_exterior:
      friendly_name: "Temperatura exterior"
      device_class: temperature
      unit_of_measurement: '°C'
      unique_id: "temperatura_exterior"
      value_template: "
      {# https://www.pacienciadigital.com/redundancia-sensores-home-assistant/ #}
      {% set sensor1 = 'sensor.aemet_temperature' %}
      {% set sensor2 = 'sensor.aemet_temperature_feeling' %}
      {% set sensor3 = 'sensor.st_quirze_del_v_vallsuau_barcelona_temperature' %}
      {% set timeout=600 %} {# tiempo límite en segundos #}
      {# establecemos código -99 si no es un número #}
      {% set sensor1_value = states(sensor1) |float |default(-99,true) %}
      {% set sensor2_value = states(sensor2) |float |default(-99,true) %}
      {% set sensor3_value = states(sensor3) |float |default(-99,true) %}
      {% set sensor1_valid=(sensor1_value!=-99) %}
      {% set sensor2_valid=(sensor1_value!=-99) %}
      {% set sensor3_valid=(sensor1_value!=-99)  %}
      {# 3 instrumentos funcionando, calculamos mediana #}
      {% if sensor1_valid and sensor2_valid and sensor3_valid %}
          {{ max(min(sensor1_value,sensor2_value), min(max(sensor1_value,sensor2_value),sensor3_value)) }}
      
      {# 2 instrumentos funcionando, calculamos media
      {% elif not sensor1_valid and sensor2_valid and sensor3_valid %}
          {{ (sensor2_value+sensor3_value)/2 }}
      {% elif sensor1_valid and not sensor2_valid and sensor3_valid %}
          {{ (sensor1_value+sensor3_value)/2 }}
      {% elif sensor1_valid and sensor2_valid and not sensor3_valid %}
          {{ (sensor1_value+sensor2_value)/2 }}
      
      {# 1 sensor funcionando, elegimos sensor operativo #}
      {% elif sensor1_valid and not sensor2_valid and not sensor3_valid %}
          {{ sensor1_value }}
      {% elif not sensor1_valid and sensor2_valid and not sensor3_valid %}
          {{ sensor2_value }}
      {% elif not sensor1_valid and not sensor2_valid and sensor3_valid %}
          {{ sensor3_value }}
      
      {# 3 instrumentos fallando #}
      {% else %}
          'Fallo'        
      {% endif %}    
      "
      icon_template: mdi:calculator

    temperatura_interior:
      friendly_name: "Temperatura interior"
      device_class: temperature
      unit_of_measurement: '°C'
      unique_id: "temperatura_interior"
      value_template: "
      {# https://www.pacienciadigital.com/redundancia-sensores-home-assistant/ #}
      {% set sensor1 = 'sensor.shelly_blu_5480_temperature' %}
      {% set sensor1_value = states(sensor1) |float |default(-99,true) %}
      {% set sensor1_valid=(sensor1_value!=-99) %}
      {# 1 sensor funcionando, elegimos sensor operativo #}
      {% if sensor1_valid  %}
          {{ sensor1_value }}
      {% else %}
          'Fallo'        
      {% endif %}    
      "
      icon_template: mdi:calculator

    humedad_interior:
      friendly_name: "Humedad interior"
      device_class: humidity
      unit_of_measurement: '%'
      unique_id: "humedad_interior"
      value_template: "
      {# https://www.pacienciadigital.com/redundancia-sensores-home-assistant/ #}
      {% set sensor1 = 'sensor.shelly_blu_5480_humidity' %}
      {% set sensor1_value = states(sensor1) |float |default(-99,true) %}
      {% set sensor1_valid=(sensor1_value!=-99) %}
      {# 1 sensor funcionando, elegimos sensor operativo #}
      {% if sensor1_valid  %}
          {{ sensor1_value }}
      {% else %}
          'Fallo'        
      {% endif %}    
      "
      icon_template: mdi:calculator

