#
# https://homeassistant-notes.notion.site/Sensores-1819be0e2c1780b28fadcaf9a0e00213
#
- platform: template
  sensors:
    sensacion_termica:
      friendly_name: "Sensación Térmica"
      unit_of_measurement: "°C"
      value_template: >
        {% from 'sensacion_termica.jinja' import macro_sensacion_termica %}
        {{ macro_sensacion_termica(states('sensor.temperatura_interior'), states('sensor.humedad_interior')) }}

    confort_termico:
      friendly_name: "Confort Térmico"
      unit_of_measurement: "°C"
      value_template: >
        {% set tempInC  = states('sensor.temperatura_interior') | float %}
        {% set humValue = states('sensor.humedad_interior') | float %}
        {% set confort = tempInC - (0.55 * (1 - 0.01 * humValue) * (tempInC - 14.5)) %}
        {{ confort | round(2) }}

    sensacion_termica_tuya_wifi_1:
      friendly_name: "Sensación Térmica (Tuya 1)"
      unit_of_measurement: "°C"
      value_template: >
        {% from 'sensacion_termica.jinja' import macro_sensacion_termica %}
        {{ macro_sensacion_termica(states('sensor.tuya_termometro_wifi_temperature'), states('sensor.tuya_termometro_wifi_humidity')) }}

    confort_termico_tuya_wifi_1:
      friendly_name: "Confort Térmico (Tuya 1)"
      unit_of_measurement: "°C"
      value_template: >
        {% set tempInC  = states('sensor.tuya_termometro_wifi_temperature') | float %}
        {% set humValue = states('sensor.tuya_termometro_wifi_humidity') | float %}
        {% set confort = tempInC - (0.55 * (1 - 0.01 * humValue) * (tempInC - 14.5)) %}
        {{ confort | round(2) }}
