input_button:
  ventilador_despacho_running:
    name: despacho running

input_select:
  ventilador_despacho_modo_auto:
    name: Modo Ventilador despacho
    options:
      - "auto"
      - "manual"

  ventilador_despacho_botonera:
    name: Selector botones ventilador
    options:
      - "Apagar"
      - "velocidad 1"
      - "velocidad 2"
      - "velocidad 3"
      - "brisa"
    initial: "Apagar"
    icon: mdi:fan

  ventilador_despacho_temporizador:
    name: Temporizador despacho
    options:
      - "idle"
      - "1"
      - "2"
      - "3"
      - "4"

timer:
  ventilador_despacho_file_timer:
    name: Timer Vent. despacho
    restore: true

sensor:
  - platform: template
    sensors:
      sensacion_termica_despacho:
        friendly_name: "Sensacion termica despacho"
        device_class: temperature
        unit_of_measurement: "°C"
        unique_id: "sensacion_termica_despacho"
        value_template: >
          {{ states('sensor.sensacion_termica_tuya_wifi_1') }}
        icon_template: mdi:thermometer

script:
  ventilador_despacho_change:
    alias: PKG VD Toggle switch según input_boolean
    description: "Activa o desactiva un switch según el estado del input_boolean"
    mode: queued
    sequence:
      - choose:
          - conditions:
              - condition: state
                entity_id: "input_boolean.ventilador_despacho_running"
                state: "on"
            sequence:
              - service: script.selector_ventilador
                data:
                  dispositivo: ventilador_despacho
                  valor: velocidad 1
          - conditions:
              - condition: state
                entity_id: "input_boolean.ventilador_despacho_running"
                state: "off"
            sequence:
              - service: script.selector_ventilador
                data:
                  dispositivo: ventilador_despacho
                  valor: Apagar

automation:
  - alias: PKG VD  Ventilador Despacho - alguien regresa
    trigger:
      - platform: state
        entity_id: input_boolean.presencia
        to: "on"

    condition: []
    action:
      - service: script.modo_ventilador
        data:
          dispositivo: ventilador_despacho
          valor: auto
    mode: single

  - alias: PKG VD Encender ventilador despacho
    trigger:
      - platform: state
        entity_id: input_boolean.ventilador_despacho
        to: "on"
    action:
      - service: script.selector_ventilador
        data:
          dispositivo: ventilador_despacho
          valor: velocidad 1

  - alias: PKG VD Apagar ventilador despacho
    trigger:
      - platform: state
        entity_id: input_boolean.ventilador_despacho
        to: "off"
    action:
      - service: script.selector_ventilador
        data:
          dispositivo: ventilador_despacho
          valor: Apagar

  - id: "ventilador_despacho_sinergia"
    alias: PKG VD Ventilador despacho - sinergia booleano/switch
    trigger:
      - platform: state
        entity_id: input_boolean.ventilador_despacho_running
    action:
      - service: script.ventilador_despacho_change
    mode: restart

  - id: "ventilador_despacho_auto"
    alias: PKG VD  Control ventilador despacho por temperatura
    description: Ajusta la velocidad del ventilador despacho según diferencia térmica (PCKG)
    trigger:
      - platform: state
        entity_id:
          - sensor.sensacion_termica_despacho
          - input_select.ventilador_despacho_modo_auto
          - input_number.ventilador_margen_calor
          - input_number.nivel_sensacion_termica_ideal
    condition:
      - condition: state
        entity_id: input_select.ventilador_despacho_modo_auto
        state: "auto"
    action:
      - variables:
          dif_temp: >
            {{ (states('sensor.sensacion_termica_despacho') | float + states('input_number.ventilador_margen_calor') | float) -
               states('input_number.nivel_sensacion_termica_ideal') | float }}
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ dif_temp <= 0.0 }}"
            sequence:
              - condition: template
                value_template: "{{ states('input_select.ventilador_despacho_botonera') != 'Apagar' }}"
              - action: script.selector_ventilador
                data:
                  dispositivo: ventilador_despacho
                  modo: auto
                  valor: Apagar

          - conditions:
              - condition: template
                value_template: "{{ dif_temp > 0.0 and dif_temp <= 1.5 }}"
            sequence:
              - condition: template
                value_template: "{{ states('input_select.ventilador_despacho_botonera') != 'velocidad 1' }}"
              - action: script.selector_ventilador
                data:
                  dispositivo: ventilador_despacho
                  modo: auto
                  valor: velocidad 1

          - conditions:
              - condition: template
                value_template: "{{ dif_temp > 1.5 and dif_temp <= 2.5 }}"
            sequence:
              - condition: template
                value_template: "{{ states('input_select.ventilador_despacho_botonera') != 'velocidad 2' }}"
              - action: script.selector_ventilador
                data:
                  dispositivo: ventilador_despacho
                  modo: auto
                  valor: velocidad 2

          - conditions:
              - condition: template
                value_template: "{{ dif_temp > 2.5 and dif_temp <= 3.0 }}"
            sequence:
              - condition: template
                value_template: "{{ states('input_select.ventilador_despacho_botonera') != 'velocidad 3' }}"
              - action: script.selector_ventilador
                data:
                  dispositivo: ventilador_despacho
                  modo: auto
                  valor: velocidad 3
          - conditions:
              - condition: template
                value_template: "{{ dif_temp > 3.0 }}"
            sequence:
              - condition: template
                value_template: "{{ states('input_select.ventilador_despacho_botonera') != 'brisa' }}"
              - action: script.selector_ventilador
                data:
                  dispositivo: ventilador_despacho
                  modo: auto
                  valor: brisa
    mode: single

  - id: "ventilador_despacho_timer_on"
    alias: PKG VD Iniciar temporizador del ventilador del despacho
    trigger:
      - platform: state
        entity_id: input_select.ventilador_despacho_temporizador
    action:
      - service: timer.start
        data:
          entity_id: timer.ventilador_despacho_file_timer
          duration: >
            {% set opt = trigger.to_state.state %}
            {% if opt == "1" %}
              00:30:00
            {% elif opt == "2" %}
              01:30:00
            {% elif opt == "3" %}
              06:00:00
            {% elif opt == "4" %}
              08:00:00
            {% else %}
              00:45:00
            {% endif %}

  - id: "ventilador_despacho_timer_off"
    alias: PKG VD timer despacho off
    description: ""
    trigger:
      - platform: state
        entity_id: timer.ventilador_despacho_file_timer
        to: idle
    condition: []
    action:
      - action: input_select.select_option
        data:
          entity_id: input_select.ventilador_despacho_temporizador
          option: idle
      - action: script.selector_ventilador
        data:
          dispositivo: ventilador_despacho
          valor: Apagar
    mode: single
