- id: "1735396993529"
  alias: Tele on Luces off
  description: ""
  triggers:
    - device_id: f2cf32e97e729a9a14fd3657ed260afe
      domain: media_player
      entity_id: 595047351c96be1289eefa62731cda3e
      type: playing
      trigger: device
  conditions: []
  actions:
    - type: turn_off
      device_id: fd3d372290728ff8c9438f0d40b84e53
      entity_id: 6eba2032971432a1ed86d5363bbd2770
      domain: switch
    - type: turn_off
      device_id: fd3d372290728ff8c9438f0d40b84e53
      entity_id: a29922953f26eb378c77a884d2f06a69
      domain: switch
  mode: single

- id: "1735397441465"
  alias: myBOx pause enciende luz 1
  description: ""
  triggers:
    - device_id: 4212ed74edbdc7e8bd7b75f3ae1a9c4c
      domain: media_player
      entity_id: e97f30b9edecdd38711ec6b28781147b
      type: idle
      trigger: device
  conditions:
    - condition: sun
      after: sunset
  actions:
    - type: turn_on
      device_id: fd3d372290728ff8c9438f0d40b84e53
      entity_id: 6eba2032971432a1ed86d5363bbd2770
      domain: switch
  mode: single

- id: "1735485273824"
  alias: NFC temporizador
  description: ""
  triggers:
    - trigger: tag
      tag_id: 37fcba90-6c4b-41cf-abef-1dea0f1c85b6
  conditions: []
  actions:
    - type: toggle
      device_id: fd3d372290728ff8c9438f0d40b84e53
      entity_id: 6eba2032971432a1ed86d5363bbd2770
      domain: switch
    - type: turn_on
      device_id: 4212ed74edbdc7e8bd7b75f3ae1a9c4c
      entity_id: 8c098c4f5799ff0d519ed64b05a880e1
      domain: remote
    - action: notify.mobile_app_sm_a155f
      metadata: {}
      data:
        message: NFC Temporizador
        title: HA NFC
  mode: single

- id: "1735500800353"
  alias: NFC lanza youtube
  description: ""
  triggers:
    - trigger: tag
      tag_id: 37fcba90-6c4b-41cf-abef-1dea0f1c85b6
  conditions: []
  actions:
    - type: turn_on
      device_id: 4212ed74edbdc7e8bd7b75f3ae1a9c4c
      entity_id: 8c098c4f5799ff0d519ed64b05a880e1
      domain: remote
    - action: media_player.play_media
      target:
        entity_id: media_player.you_box
      data:
        media_content_type: url
        media_content_id: https://www.youtube.com/playlist?list=PLjF50Dlp9ienDb1cqXQOSDgNZFC-tVdya
  mode: single

- id: "1735542263430"
  alias: despertador 1
  description: ""
  use_blueprint:
    path: Blackshome/timer.yaml
    input:
      entity_input:
        area_id: bedroom
      trigger_one_time: 07:50:00
      trigger_one_duration:
        hours: 0
        minutes: 30
        seconds: 0
      weekday_options:
        - mon
        - tue
        - wed
        - thu
        - fri

- id: "1735560626804"
  alias: Calendar DL
  description: ""
  triggers:
    - trigger: calendar
      entity_id: calendar.domotica
      event: start
      offset: -0:5:0
  conditions: []
  actions:
    - device_id: 2e125cc8a76db2210a51672189f23b01
      domain: mobile_app
      type: notify
      message:
        Calendar {{ trigger.calendar_event.summary }} at {{trigger.calendar_event.start
        }}
  mode: single

- id: "1735563377877"
  alias: Atardecer
  description: ""
  triggers:
    - trigger: sun
      event: sunset
      offset: 00:05:00
  conditions:
    - condition: zone
      entity_id: device_tracker.sm_a155f
      zone: zone.home
  actions:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        device_id: a2f77cddd9878b9d3b8af396fcf240ad
  mode: single

- id: "1735563455807"
  alias: Amanecer
  description: ""
  triggers:
    - trigger: sun
      event: sunrise
      offset: 0
  conditions: []
  actions:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        label_id: luz
  mode: single

- id: "1735739612217"
  alias: NFC Temporizador Helper
  description: ""
  triggers:
    - trigger: tag
      tag_id: 37fcba90-6c4b-41cf-abef-1dea0f1c85b6
  conditions: []
  actions:
    - entity_id: timer.cocina_10m
      action: timer.start
    - action: tts.speak
      metadata: {}
      data:
        cache: true
        message: "inicio temporal "
        media_player_entity_id: media_player.my_box_2
  mode: single
