#
# https://homeassistant-notes.notion.site/Sensores-1819be0e2c1780b28fadcaf9a0e00213
# https://www.pacienciadigital.com/redundancia-sensores-home-assistant/
#
- platform: template
  sensors:
    humedad_exterior:
      friendly_name: "Humedad Exterior"
      device_class: humidity
      unit_of_measurement: '%'
      unique_id: "humedad_exterior"
      value_template: "
      {% set sensor1 = 'sensor.aemet_humidity' %}
      {% set sensor2 = 'sensor.st_quirze_del_v_vallsuau_barcelona_humidity' %}
      {% set timeout=600 %} {# tiempo límite en segundos #}
      {# establecemos código -99 si no es un número #}
      {% set sensor1_value = states(sensor1) |float |default(-99,true) %}
      {% set sensor2_value = states(sensor2) |float |default(-99,true) %}
      {% set sensor1_valid=(sensor1_value!=-99) %}
      {% set sensor2_valid=(sensor1_value!=-99) %}
      {% if sensor1_valid and sensor2_valid  %}
          {{ (sensor1_value+sensor2_value)/2 }}      
      {% elif sensor1_valid and not sensor2_valid %}
          {{ sensor1_value }}
      {% elif sensor2_valid and not sensor1_valid %}
          {{ sensor2_value }}
      
      {# 3 instrumentos fallando #}
      {% else %}
          'Fallo'        
      {% endif %}    
      "
      icon_template: mdi:calculator

