#
# https://homeassistant-notes.notion.site/Sensores-1819be0e2c1780b28fadcaf9a0e00213
# https://www.pacienciadigital.com/redundancia-sensores-home-assistant/
#
- platform: template
  sensors:
    humedad_exterior:
      friendly_name: "H. Exterior"
      device_class: humidity
      unit_of_measurement: "%"
      unique_id: "humedad_exterior"
      value_template: >
        {% from '1oo2.jinja' import macro_1oo2 %}
        {{ macro_1oo2('sensor.aemet_humidity','sensor.st_quirze_del_v_vallsuau_barcelona_humidity') }}

      icon_template: mdi:calculator
