#
# https://homeassistant-notes.notion.site/Sensores-1819be0e2c1780b28fadcaf9a0e00213
# https://www.pacienciadigital.com/redundancia-sensores-home-assistant/
#
- platform: template
  sensors:
    temperatura_exterior:
      friendly_name: "T. exterior"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "temperatura_exterior"
      value_template: >
        {% from '2oo3.jinja' import macro_2oo3 %}
        {{ macro_2oo3('sensor.aemet_temperature','sensor.temperatura_localidad','sensor.aemet_temperature_feeling') }}
      icon_template: mdi:thermometer
