- platform: group
  name: "Alias Caldera"
  unique_id: "alias_caldera"
  entities:
    - switch.shelly1minig3_3030f9e91908_switch_0

- platform: group
  name: "Alias Calefactor"
  unique_id: "alias_calefactor"
  entities:
    - switch.zigbee_nous_enchufe_01
