#
# https://homeassistant-notes.notion.site/Sensores-1819be0e2c1780b28fadcaf9a0e00213
#
- platform: template
  sensors:
    sensacion_termica:
      friendly_name: "Sensación Térmica"
      unit_of_measurement: "°C"
      value_template: >
        {% from 'sensacion_termica.jinja' import macro_sensacion_termica %}
        {{ macro_sensacion_termica('sensor.temperatura_interior','sensor.humedad_interior') }}

    confort_termico:
      friendly_name: "Confort Térmico"
      unit_of_measurement: "°C"
      value_template: >
        {% from 'confort_termico.jinja' import macro_confort_termico %}
        {{ macro_confort_termico('sensor.temperatura_interior', 'sensor.humedad_interior') }}
    #
    #   Tuya 1
    #
    sensacion_termica_tuya_wifi_1:
      friendly_name: "Sensación Térmica (Tuya 1)"
      unit_of_measurement: "°C"
      value_template: >
        {% from 'sensacion_termica.jinja' import macro_sensacion_termica %}
        {{ macro_sensacion_termica('sensor.tuya_termometro_wifi_temperature', 'sensor.tuya_termometro_wifi_humidity') }}

    confort_termico_tuya_wifi_1:
      friendly_name: "Confort Térmico (Tuya 1)"
      unit_of_measurement: "°C"
      value_template: >
        {% from 'confort_termico.jinja' import macro_confort_termico %}
        {{ macro_confort_termico('sensor.tuya_termometro_wifi_temperature','sensor.tuya_termometro_wifi_humidity') }}

    sensacion_termica_despacho:
      friendly_name: "Sensacion termica despacho"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "sensacion_termica_despacho"
      value_template: >
        {{ states('sensor.sensacion_termica_tuya_wifi_1') }}
      icon_template: mdi:thermometer

    #
    #   zigbee_sonoff_snzb02_01
    #

    sensacion_termica_zigbee_sonoff_snzb02_01:
      friendly_name: "Sensación Térmica (Tuya 1)"
      unit_of_measurement: "°C"
      value_template: >
        {% from 'sensacion_termica.jinja' import macro_sensacion_termica %}
        {{ macro_sensacion_termica('sensor.zigbee_sonoff_snzb02_01_temperature', 'sensor.zigbee_sonoff_snzb02_01_humidity') }}

    confort_termico_zigbee_sonoff_snzb02_01:
      friendly_name: "Confort Térmico (Tuya 1)"
      unit_of_measurement: "°C"
      value_template: >
        {% from 'confort_termico.jinja' import macro_confort_termico %}
        {{ macro_confort_termico('sensor.zigbee_sonoff_snzb02_01_temperature','sensor.zigbee_sonoff_snzb02_01_humidity') }}

    sensacion_termica_habitacion:
      friendly_name: "Sensacion termica habitacion"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "sensacion_termica_habitacion"
      value_template: >
        {{ states('sensor.sensacion_termica_zigbee_sonoff_snzb02_01') }}
      icon_template: mdi:thermometer
