#
# https://homeassistant-notes.notion.site/Sensores-1819be0e2c1780b28fadcaf9a0e00213
#

- platform: template
  sensors:
    temperatura_objetivo_minima:
      friendly_name: "T. target min"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "temperatura_objetivo_minima"
      value_template: >
        {% from 'trvs.jinja' import trvs %}
        {{ trvs('temperature','min') }}
      icon_template: mdi:thermometer
