#
# https://homeassistant-notes.notion.site/Sensores-1819be0e2c1780b28fadcaf9a0e00213
# https://www.pacienciadigital.com/redundancia-sensores-home-assistant/
#
- platform: template
  sensors:
    temperatura_interior:
      friendly_name: "T. interior"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "temperatura_interior"
      value_template: >
        {% from '1oo2.jinja' import macro_1oo2 %}
        {{ macro_1oo2('sensor.shelly_blu_5480_temperature','sensor.zigbee_sonoff_snzb02_01_temperature') }}
      icon_template: mdi:thermometer
