#
# https://homeassistant-notes.notion.site/Sensores-1819be0e2c1780b28fadcaf9a0e00213
#
- platform: template
  sensors:
    temperatura_interior:
      friendly_name: "T. termostato caldera"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "temperatura_caldera" ## renombrado en UI !
      value_template: >
        {{ states('sensor.temperatura_real_max_2') }}
      icon_template: mdi:thermometer
