- platform: template
  sensors:
    temperatura_prediccion_ia:
      friendly_name: "T. Prediccion IA"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "temperatura_prediccion_ia" ## renombrado en UI !
      value_template: >
        {{ state_attr('sensor.influxdb_output', 'temperature') }}
      icon_template: mdi:thermometer
